#ifndef KEYWORDS_H_
#define KEYWORDS_H_

typedef struct KeywordResult {
	const char *name;
	enum TokenType type;
} KeywordResult;

// keyword lookup function generated by gperf
KeywordResult *KeywordLookup(register const char *str, register size_t len);

#endif /* KEYWORDS_H_ */

